### PR TITLE
feat: FORMALIZATION_FORMAT_PUSH

### PR DESCRIPTION
**Pull request by jiho-kr**
http://git.sphd.io/support/stt-issues/issues/854

support `FORMALIZATION_FORMAT_PUSH`

use Template string

It is used as follows.

```
FORMALIZATION_FORMAT_PUSH = '{"type":"push_all", "resource": [{"resource": "ToastMessage", "path": "$", "body": { "cmd": ${obj.cmd}}, "resource":${JSON.stringify(obj.opts)}}]}'
```

### CODE REVIEW

**Comment by heycalmdown** [comment]
Two things are popped up in my mind -

* Is it a good solution which formalizes the object in the island.js, not in the push-island?
* Is it the only option for us having some risk by using `eval`?

**Comment by jiho-kr** [comment]
Is it a good solution which formalizes the object in the island.js, not in the push-island?

- I think it would be a good solution to be in the push-island like global variables.
- but it is a big problem if there is an island that has already been used push format and should not be affected by `FORMALIZATION_FORMAT_PUSH`.

Is it the only option for us having some risk by using eval?

- I do not have any other than 'eval' ideas right now.
- because the push message is a free format and the interface that the game team wants is also free format.

**Comment by d3m3vilurr** [comment]
`eval` is really bad idea.

1. `eval` can break javascript optimizer.
2. we don't know input value. it can be vuln spot.
3. data looks still not useful. cuz `obj.opts` is still unacceptable (at least our product)
4. all push messages can have the different format and can contain different data set. so IMHO, we need message format map not the one generic format. hm...

**Comment by jiho-kr** [comment]
eval can break javascript optimizer.
- If there is a better way, eval will be replaced.

we don't know input value. it can be vuln spot.
- I think this environment will be managed by the island platform engineer.
- I think this environment will accommodate the requirements of the various PUSH formats.

data looks still not useful. cuz obj.opts is still unacceptable (at least our product)
- if set up as a sample,
```
org message : { cmd: 'push cmd',  opts: { messageType: 'broadcast', message: 'message' } }
FORMALIZATION message
{  type:"push_all",
   resource: [
     {resource: "ToastMessage",
      path: "$",
      body: {  cmd: "push cmd"}, 
      resource: { messageType: "broadcast", message:"message" }
     }
  ]
}
```
all push messages can have the different format and can contain different data set. so IMHO, we need message format map not the one generic format. hm...
- This function only changes the message format('{cmd:?, opts:?') provided by common island to another format.
The push messages on the common island are all the same format. Generally, features can be added but are not modified (break changed issue)
If `resource:" ToastMessage "` is a problem, the feature to distinguish messages from the common island should be added.

**Comment by d3m3vilurr** [comment]
1. yeah we should find other option. I thought template literal could work like python and other modern languages. :/
2. discussed in the offline. if doesn't unpack the packet in the leaf node, this approach is probably right. but the if always unpack the packet in the leaf, we can get another useful spot.

**Pull request merged**
